name: GitHub Pages

on:
  push:
    branches:
      - main
      - dev
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python3 -m pip install mkdocs
          python3 -m pip install mkdocs-material
          python3 -m pip install mkdocs-include-markdown-plugin==3.8.1
          python3 -m pip install mkdocs-macros-plugin

      - name: Build mkdocs
        run: |
          mkdocs build -f ./docs/mkdocs.en.yml
          mkdocs build -f ./docs/mkdocs.zh.yml
          mkdocs build -f ./docs/mkdocs.ja.yml
          cp -av ./docs/index.html ./docs/site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
          publish_branch: gh-pages
